### ISSUE TITLE
New benchmark functions

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [ssydasheng/Neural-Kernel-Network#1]
Hi Shengyang,

I wanted to try your algorithm on other benchmark functions such as Rosenbrock and I changed the code in 'bo_functions.py  as the following:

```
def rosenbrock(x):
    d = 4
    x = x[:, :d] [0] # This is so that if the input is high dimensional, only 4 dimensions, be effective.
    y = 0
    for i in range(d - 1):
        y += 100 * (x[i + 1] - x[i] ** 2) ** 2
        y += (x[i] - 1) ** 2
    return tf.reshape(y,[1])

class Rosenbrock(Function):
    def __init__(self, num_dims):
        self.num_dims = num_dims

    @property
    def min(self):
        return 0. * np.ones([self.num_dims], dtype=FLOAT_TYPE)

    @property
    def max(self):
        return 1. * np.ones([self.num_dims], dtype=FLOAT_TYPE)

    def func(self, x):
        return rosenbrock(x)

    @property
    def name(self):
        return 'Rosenbrock'

```

If I understood correctly, since the bounds for Rosenbrock is between [0,1] the class Rosenbrock should have been defined as above.

In the bayes_opt.py file also I added the following lines similar to other functions:

```
    if args.name == 'Rosenbrock':
        Task = Rosenbrock(num_dims=input_dim)
        dim_groups = [[id] for id in range(input_dim)]
```

But I get an error for it, and wanted to ask if in the first place the way I have defined these functions are correct. 

Here's also a part of the error:

> Epoch 1 of 100:
> Traceback (most recent call last):
>   File "/home/ics/ranjbar/.local/share/virtualenvs/NKN_venv-V8ztIfaw/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
>     return fn(*args)
>   File "/home/ics/ranjbar/.local/share/virtualenvs/NKN_venv-V8ztIfaw/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "/home/ics/ranjbar/.local/share/virtualenvs/NKN_venv-V8ztIfaw/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Input matrix is not invertible.
> 	 [[{{node likelihood_1/MatrixTriangularSolve}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "exp/bayes-opt.py", line 110, in <module>
>     bo_model.optimize(num_iters, 'bo/{}_{}/{}_{}'.format(args.name,input_dim, args.kern, args.run))
>   File "/home/ics/ranjbar/BO/BO_3/External_codes/Neural-Kernel-Network/bayesianOpt.py", line 122, in optimize
>     self._train(i)
>   File "/home/ics/ranjbar/BO/BO_3/External_codes/Neural-Kernel-Network/bayesianOpt.py", line 62, in _train
>     feed_dict={self.X_ph: self.X, self.y_ph: self.y
>   File "/home/ics/ranjbar/.local/share/virtualenvs/NKN_venv-V8ztIfaw/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
>     run_metadata_ptr)
>   File "/home/ics/ranjbar/.local/share/virtualenvs/NKN_venv-V8ztIfaw/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/home/ics/ranjbar/.local/share/virtualenvs/NKN_venv-V8ztIfaw/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
>     run_metadata)
>   File "/home/ics/ranjbar/.local/share/virtualenvs/NKN_venv-V8ztIfaw/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Input matrix is not invertible.
> 	 [[node likelihood_1/MatrixTriangularSolve (defined at /home/ics/ranjbar/BO/BO_3/External_codes/Neural-Kernel-Network/NKN_venv/GPflow-Slim/gpflowSlim/densities.py:82) ]]
> 
> Errors may have originated from an input operation.
> Input Source operations connected to node likelihood_1/MatrixTriangularSolve:
>  likelihood_1/sub (defined at /home/ics/ranjbar/BO/BO_3/External_codes/Neural-Kernel-Network/NKN_venv/GPflow-Slim/gpflowSlim/densities.py:81)	
>  likelihood_1/Cholesky (defined at /home/ics/ranjbar/BO/BO_3/External_codes/Neural-Kernel-Network/NKN_venv/GPflow-Slim/gpflowSlim/models/gpr.py:70)
> 
> Original stack trace for 'likelihood_1/MatrixTriangularSolve':
>   File "exp/bayes-opt.py", line 107, in <module>
>     Task.min, Task.max, iterations=iterations)
>   File "/home/ics/ranjbar/BO/BO_3/External_codes/Neural-Kernel-Network/bayesianOpt.py", line 30, in __init__
>     self.init_graph()
>   File "/home/ics/ranjbar/BO/BO_3/External_codes/Neural-Kernel-Network/bayesianOpt.py", line 47, in init_graph
>     self.loss = self.model.objective
>   File "/home/ics/ranjbar/BO/BO_3/External_codes/Neural-Kernel-Network/NKN_venv/GPflow-Slim/gpflowSlim/models/model.py", line 70, in objective
>     self.likelihood_tensor,
>   File "/home/ics/ranjbar/BO/BO_3/External_codes/Neural-Kernel-Network/NKN_venv/GPflow-Slim/gpflowSlim/models/model.py", line 55, in likelihood_tensor
>     return self._build_likelihood()
>   File "/home/ics/ranjbar/BO/BO_3/External_codes/Neural-Kernel-Network/NKN_venv/GPflow-Slim/gpflowSlim/decors.py", line 33, in runnable
>     return method(*args, **kwargs)
>   File "/home/ics/ranjbar/BO/BO_3/External_codes/Neural-Kernel-Network/NKN_venv/GPflow-Slim/gpflowSlim/models/gpr.py", line 72, in _build_likelihood
>     return multivariate_normal(self.Y, m, L)
>   File "/home/ics/ranjbar/BO/BO_3/External_codes/Neural-Kernel-Network/NKN_venv/GPflow-Slim/gpflowSlim/densities.py", line 82, in multivariate_normal
>     alpha = tf.matrix_triangular_solve(L, d, lower=True)
>   File "/home/ics/ranjbar/.local/share/virtualenvs/NKN_venv-V8ztIfaw/lib/python3.6/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 1878, in matrix_triangular_solve
>     adjoint=adjoint, name=name)
>   File "/home/ics/ranjbar/.local/share/virtualenvs/NKN_venv-V8ztIfaw/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
>     op_def=op_def)
>   File "/home/ics/ranjbar/.local/share/virtualenvs/NKN_venv-V8ztIfaw/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/home/ics/ranjbar/.local/share/virtualenvs/NKN_venv-V8ztIfaw/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
>     op_def=op_def)
>   File "/home/ics/ranjbar/.local/share/virtualenvs/NKN_venv-V8ztIfaw/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
>     self._traceback = tf_stack.extract_stack()
> 

Thanks.

**Comment by ssydasheng** [comment]
Hi, Alireza,

If you have tried my code with the Stybtang function, you must have found that the "Stybtang" function receives a tensor of shape `[None, d]` and outputs a tensor of shape `[None]`.

However, in your implementation of the "Rosenbrock" function, you receives a tensor of shape [None, d] but outputs a scalar. The first problem I noticed is in the line `x = x[:, :d] [0] `, it makes no sense to have the last `[0]` operation.

Please have a check with this.

**Comment by a-z-e-r-i-l-a** [comment]
Hi,

So I did the following experiment:

```
def stybtang(x):
    if len(x.shape) == 1:
        return 0.5 * tf.reduce_sum(tf.pow(x, 4) - 16 * tf.pow(x, 2) + 5 * x)
    else:
        return 0.5 * tf.reduce_sum(tf.pow(x, 4) - 16 * tf.pow(x, 2) + 5 * x, axis=1)
```
```
x = tf.constant([2.,1., 5.])
print(stybtang(x))

sess = tf.Session()
with sess.as_default():
    print(stybtang(x).eval())
```
output:
> Tensor("mul_29:0", shape=(), dtype=float32)
> 101.0

```
`x = tf.constant([[2.,1., 5.]])
print(stybtang(x))

sess = tf.Session()
with sess.as_default():
    print(stybtang(x).eval())`
```
output:

> Tensor("Reshape_6:0", shape=(1,), dtype=float32)
> [101.]

Then I tried the same with the rosenbrock function I had written:

```
def Rosenbrock(x):
    d = 2
    if len(x.shape) == 1:
        y = 0
        for i in range(d - 1):
            y += 100 * (x[i + 1] - x[i] ** 2) ** 2
            y += (x[i] - 1) ** 2
        return y
        
    else:
        x = x[:,:d][0]
        y = 0
        for i in range(d - 1):
            y += 100 * (x[i + 1] - x[i] ** 2) ** 2
            y += (x[i] - 1) ** 2
            
        return tf.reshape(y,[1])
```
```
x = tf.constant([2.,1., 5.])
print(Rosenbrock(x))

sess = tf.Session()
with sess.as_default():
    print(Rosenbrock(x).eval())
```
output:
> Tensor("add_29:0", shape=(), dtype=float32)
> 901.0

```
x = tf.constant([[2.,1., 5.]])
print(Rosenbrock(x))

sess = tf.Session()
with sess.as_default():
    print(Rosenbrock(x).eval())

```
output:
> Tensor("Reshape_4:0", shape=(1,), dtype=float32)
> [901.]

The inputs and outputs seems similar in shape but I still get the earlier error when I use this function.

**Comment by ssydasheng** [comment]
Hi, Alireza,

The problem is that your Rosenbrock implementation doesn't support multiple xs. If you create `x` of shape [2, 3], you will find the problem.

**Comment by a-z-e-r-i-l-a** [comment]
> Hi, Alireza,
> 
> The problem is that your Rosenbrock implementation doesn't support multiple xs. If you create `x` of shape [2, 3], you will find the problem.

Thank you again, your suggestion worked.
